### ISSUE TITLE
myAMC - sub dir's for the filter.ini

### ISSUE THREAD

**Issue by b4dr1ck** [sueswe/my_amc#1]
Hey Folk,

can you create the possibility to read multiple fillter.ini files, stored in different sub-dir's?
So I could create for each kind of project a certain filter.ini.

Thx 
BadRick ;)

**Comment by sueswe** [comment]
Would it be okay to implement more ini-files in just _one_ configuration directory?

**Comment by sueswe** [comment]
See Release 0.2.6.0 : https://github.com/sueswe/my_amc/releases/tag/0.2.6.0
