### ISSUE TITLE
myAmc - attachment - same filename

### ISSUE THREAD

**Issue by b4dr1ck** [sueswe/my_amc#2]
Yo Guy,

can you please implement the feature, do save multiple files from the mail-attachment with the same filename. 
Maybe automatically rename the files with a counter at the end of each filename (file1.txt, file2.txt,....)

Thx
Bad-Rick

**Comment by sueswe** [comment]
Done!
https://github.com/sueswe/my_amc/releases/tag/0.2.7.1
