### ISSUE TITLE
response-mail after amc-action

### ISSUE THREAD

**Issue by b4dr1ck** [sueswe/my_amc#3]
wäre nett in der ini ev. ein Adresse inkl. Mailtext konfigurieren zu können, die im Fehlerfall /oder aber auch wenn der AMC Aufruf funktioniert hat) eine E-Mail sendet an die konfigurierte Adresse(n).
Ev. auch mit angehängtem Log-File (welches man dann auch konfigurieren kann)

Beispiel:
fail_address=foo@bar.com
fail_body="the amc action failed. For, more details check the log"
fail_log="/foo/bar/the_log.txt"

**Comment by sueswe** [comment]
coole Idee - werd mich dran machen

**Comment by sueswe** [comment]
DONE.
